# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - run: mkdir public
      - run: echo "default folder $GITHUB_ACTION_PATH"
      - run: ls /123
      - run: sudo apt-get update && sudo apt-get -y upgrade
      - run: sudo apt install -y build-essential debhelper dh-python git asciidoc intltool libpython3-dev libssl-dev libsystemd-dev python3-dev pkg-config systemd xsltproc docbook-xsl wget cargo intltool
      - run: wget https://source.ipfire.org/releases/libloc/libloc-0.9.16.tar.gz
      - run: echo "2092361f0c76b31e65aed85692c56176996925e1cd5d78d113ab9c53ba27f3fc libloc-0.9.16.tar.gz" | sha256sum -c
      - run: tar xf libloc-0.9.16.tar.gz
      - working-directory: ./libloc-0.9.16
        run: ./autogen.sh
      - working-directory: ./libloc-0.9.16
        run: ./configure CFLAGS='-g -O0' --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib --with-database-path=${{env.working-directory}}/database.db
      - working-directory: ./libloc-0.9.16
        run: make
      - working-directory: ./libloc-0.9.16
        run: sudo make install
      - run: ls /usr/lib/python3.9/site-packages
      - run: git clone --depth 1 https://git.torproject.org/tor.git
      - run: PYTHONPATH=/usr/lib/python3.9/site-packages location --quiet update
      - run: PYTHONPATH=/usr/lib/python3.9/site-packages location dump ${{env.working-directory}}/public/geoip-dump.txt
      - run: version=$(date --date="$(PYTHONPATH=/usr/lib/python3.9/site-packages location version)" '+%Y%m%dT%H%m%SZ')
      - working-directory: tor/scripts/maint/geoip/geoip-db-tool
        run: cargo run --release -- -i ${{env.working-directory}}/public/geoip-dump.txt
      - run: mv tor/scripts/maint/geoip/geoip-db-tool/geoip{,6} public/
      - run: cp -r index.html countries.txt static public/
      - run: sed -i "s,VERSION,${version}," public/index.html
      - run: printf "$version" > public/version  
